/* Régiments, bâtiments et technologies.
   Les distances sont en mètres et les durées en secondes de bataille :
   les mêmes chiffres servent à la campagne (coût, entretien) et au combat. */
(function (G) {
  'use strict';

  /* Catégories d'unités, pour l'IA, les icônes et les bonus de doctrine. */
  const CATEGORIES = {
    milice:        { nom: 'Milice',            classe: 'infanterie' },
    ligne:         { nom: 'Infanterie de ligne', classe: 'infanterie' },
    legere:        { nom: 'Infanterie légère',  classe: 'infanterie' },
    grenadiers:    { nom: 'Grenadiers',         classe: 'infanterie' },
    garde:         { nom: 'Garde',              classe: 'infanterie' },
    dragons:       { nom: 'Dragons',            classe: 'cavalerie' },
    cavalerie:     { nom: 'Cavalerie de ligne', classe: 'cavalerie' },
    lourde:        { nom: 'Cavalerie lourde',   classe: 'cavalerie' },
    hussards:      { nom: 'Cavalerie légère',   classe: 'cavalerie' },
    canon:         { nom: 'Artillerie de campagne', classe: 'artillerie' },
    obusier:       { nom: 'Obusier',            classe: 'artillerie' },
    general:       { nom: 'État-major',         classe: 'commandement' },
  };

  /* Un régiment :
     hommes   effectif à plein
     cout     recrutement (une fois)     entretien  par saison
     melee / defense / charge            combat au corps à corps
     portee   en mètres, 0 = pas d'arme à feu
     precision, rechargement (s), degats (probabilité de mise hors de combat par balle au but)
     moral, discipline (vitesse de ralliement et tenue en ligne), vitesse (m/s)
     requis   { batiment: niveau }       tech  identifiant de technologie requise */
  const UNITS = [
    /* --- Occident --- */
    { id: 'milice', nom: 'Milice bourgeoise', cat: 'milice', cultures: ['occident'], hommes: 120,
      cout: 380, entretien: 60, melee: 5, defense: 4, charge: 3, armure: 0,
      portee: 80, precision: 0.26, rechargement: 26, degats: 0.55,
      moral: 5, discipline: 0.5, vitesse: 2.0, requis: {} },
    { id: 'ligne', nom: 'Infanterie de ligne', cat: 'ligne', cultures: ['occident'], hommes: 120,
      cout: 700, entretien: 110, melee: 8, defense: 7, charge: 4, armure: 0,
      portee: 105, precision: 0.36, rechargement: 21, degats: 0.62,
      moral: 9, discipline: 0.75, vitesse: 2.1, requis: { caserne: 1 } },
    { id: 'fusiliers', nom: 'Fusiliers légers', cat: 'legere', cultures: ['occident'], hommes: 80,
      cout: 640, entretien: 100, melee: 7, defense: 6, charge: 4, armure: 0,
      portee: 140, precision: 0.50, rechargement: 25, degats: 0.70,
      moral: 8, discipline: 0.65, vitesse: 2.6, requis: { caserne: 2 }, tirailleur: true },
    { id: 'grenadiers', nom: 'Grenadiers', cat: 'grenadiers', cultures: ['occident'], hommes: 100,
      cout: 980, entretien: 155, melee: 12, defense: 9, charge: 8, armure: 0,
      portee: 105, precision: 0.38, rechargement: 20, degats: 0.64,
      moral: 12, discipline: 0.85, vitesse: 2.2, requis: { caserne: 2 }, grenades: true },
    { id: 'garde', nom: 'Gardes à pied', cat: 'garde', cultures: ['occident'], hommes: 120,
      cout: 1400, entretien: 220, melee: 13, defense: 11, charge: 8, armure: 0,
      portee: 110, precision: 0.42, rechargement: 18, degats: 0.66,
      moral: 15, discipline: 0.95, vitesse: 2.2, requis: { caserne: 3, ecole: 1 } },
    { id: 'dragons', nom: 'Dragons', cat: 'dragons', cultures: ['occident'], hommes: 60,
      cout: 900, entretien: 150, melee: 9, defense: 7, charge: 10, armure: 1,
      portee: 70, precision: 0.28, rechargement: 30, degats: 0.58,
      moral: 9, discipline: 0.7, vitesse: 5.2, requis: { ecuries: 1 }, monte: true },
    { id: 'cavalerie', nom: 'Cavalerie de ligne', cat: 'cavalerie', cultures: ['occident'], hommes: 60,
      cout: 1050, entretien: 175, melee: 12, defense: 8, charge: 16, armure: 1,
      portee: 0, precision: 0, rechargement: 0, degats: 0,
      moral: 11, discipline: 0.75, vitesse: 6.0, requis: { ecuries: 1 }, monte: true },
    { id: 'cuirassiers', nom: 'Cuirassiers', cat: 'lourde', cultures: ['occident'], hommes: 50,
      cout: 1500, entretien: 240, melee: 15, defense: 12, charge: 22, armure: 3,
      portee: 0, precision: 0, rechargement: 0, degats: 0,
      moral: 14, discipline: 0.85, vitesse: 5.6, requis: { ecuries: 2 }, monte: true },
    { id: 'canon6', nom: 'Canon de 6 livres', cat: 'canon', cultures: ['occident', 'orient'], hommes: 24, pieces: 4,
      cout: 900, entretien: 140, melee: 3, defense: 3, charge: 2, armure: 0,
      portee: 520, precision: 0.60, rechargement: 22, degats: 1.0,
      moral: 6, discipline: 0.6, vitesse: 1.4, requis: { fonderie: 1 }, canon: true },
    { id: 'canon12', nom: 'Canon de 12 livres', cat: 'canon', cultures: ['occident', 'orient', 'ottoman'], hommes: 28, pieces: 4,
      cout: 1300, entretien: 200, melee: 3, defense: 3, charge: 2, armure: 0,
      portee: 680, precision: 0.58, rechargement: 27, degats: 1.5,
      moral: 6, discipline: 0.6, vitesse: 1.0, requis: { fonderie: 2 }, canon: true },
    { id: 'obusier', nom: 'Obusier', cat: 'obusier', cultures: ['occident', 'orient', 'ottoman'], hommes: 24, pieces: 4,
      cout: 1400, entretien: 210, melee: 3, defense: 3, charge: 2, armure: 0,
      portee: 600, precision: 0.34, rechargement: 30, degats: 1.2,
      moral: 6, discipline: 0.6, vitesse: 1.2, requis: { fonderie: 2 }, canon: true, explosif: true },

    /* --- Orient (Russie, Pologne) --- */
    { id: 'streltsy', nom: 'Streltsy', cat: 'milice', cultures: ['orient'], hommes: 140,
      cout: 480, entretien: 75, melee: 8, defense: 5, charge: 5, armure: 0,
      portee: 85, precision: 0.26, rechargement: 28, degats: 0.60,
      moral: 7, discipline: 0.45, vitesse: 2.0, requis: {} },
    { id: 'ligne_est', nom: 'Infanterie de ligne', cat: 'ligne', cultures: ['orient'], hommes: 140,
      cout: 660, entretien: 105, melee: 8, defense: 7, charge: 4, armure: 0,
      portee: 100, precision: 0.31, rechargement: 24, degats: 0.60,
      moral: 8, discipline: 0.6, vitesse: 2.0, requis: { caserne: 1 } },
    { id: 'grenadiers_est', nom: 'Grenadiers', cat: 'grenadiers', cultures: ['orient'], hommes: 110,
      cout: 940, entretien: 150, melee: 12, defense: 9, charge: 8, armure: 0,
      portee: 100, precision: 0.33, rechargement: 22, degats: 0.62,
      moral: 11, discipline: 0.75, vitesse: 2.1, requis: { caserne: 2 }, grenades: true },
    { id: 'hussards_ailes', nom: 'Hussards ailés', cat: 'lourde', cultures: ['orient'], hommes: 50,
      cout: 1600, entretien: 250, melee: 16, defense: 12, charge: 28, armure: 3,
      portee: 0, precision: 0, rechargement: 0, degats: 0,
      moral: 15, discipline: 0.8, vitesse: 6.0, requis: { ecuries: 2 }, monte: true, national: ['pol'] },
    { id: 'cosaques', nom: 'Cosaques', cat: 'hussards', cultures: ['orient'], hommes: 60,
      cout: 700, entretien: 115, melee: 9, defense: 5, charge: 11, armure: 0,
      portee: 60, precision: 0.22, rechargement: 30, degats: 0.5,
      moral: 8, discipline: 0.4, vitesse: 7.0, requis: { ecuries: 1 }, monte: true, harcelement: true },

    /* --- Ottoman --- */
    { id: 'azabs', nom: 'Azabs', cat: 'milice', cultures: ['ottoman'], hommes: 150,
      cout: 340, entretien: 55, melee: 7, defense: 4, charge: 6, armure: 0,
      portee: 70, precision: 0.22, rechargement: 30, degats: 0.55,
      moral: 6, discipline: 0.35, vitesse: 2.2, requis: {} },
    { id: 'janissaires', nom: 'Janissaires', cat: 'ligne', cultures: ['ottoman'], hommes: 120,
      cout: 820, entretien: 130, melee: 13, defense: 8, charge: 8, armure: 1,
      portee: 115, precision: 0.38, rechargement: 26, degats: 0.66,
      moral: 13, discipline: 0.6, vitesse: 2.3, requis: { caserne: 1 } },
    { id: 'janissaires_garde', nom: 'Janissaires de la Porte', cat: 'garde', cultures: ['ottoman'], hommes: 120,
      cout: 1450, entretien: 230, melee: 16, defense: 11, charge: 11, armure: 2,
      portee: 115, precision: 0.42, rechargement: 24, degats: 0.68,
      moral: 16, discipline: 0.7, vitesse: 2.3, requis: { caserne: 3, ecole: 1 } },
    { id: 'sipahis', nom: 'Sipahis', cat: 'cavalerie', cultures: ['ottoman'], hommes: 60,
      cout: 980, entretien: 160, melee: 13, defense: 8, charge: 15, armure: 2,
      portee: 0, precision: 0, rechargement: 0, degats: 0,
      moral: 11, discipline: 0.55, vitesse: 6.2, requis: { ecuries: 1 }, monte: true },
    { id: 'deli', nom: 'Deli', cat: 'hussards', cultures: ['ottoman'], hommes: 60,
      cout: 640, entretien: 105, melee: 10, defense: 4, charge: 13, armure: 0,
      portee: 0, precision: 0, rechargement: 0, degats: 0,
      moral: 12, discipline: 0.3, vitesse: 7.2, requis: { ecuries: 1 }, monte: true, harcelement: true },
    { id: 'canon_ott', nom: 'Grande pièce ottomane', cat: 'canon', cultures: ['ottoman'], hommes: 32, pieces: 3,
      cout: 1200, entretien: 190, melee: 3, defense: 3, charge: 2, armure: 0,
      portee: 740, precision: 0.48, rechargement: 34, degats: 1.8,
      moral: 6, discipline: 0.5, vitesse: 0.8, requis: { fonderie: 1 }, canon: true },

    /* --- Commandement, toutes cultures --- */
    { id: 'general', nom: 'État-major', cat: 'general', cultures: ['occident', 'orient', 'ottoman'], hommes: 20,
      cout: 0, entretien: 90, melee: 12, defense: 10, charge: 12, armure: 2,
      portee: 0, precision: 0, rechargement: 0, degats: 0,
      moral: 16, discipline: 0.9, vitesse: 6.4, requis: {}, monte: true, general: true },
  ];

  /* Bâtiments : chaînes à plusieurs niveaux, un chantier à la fois par province. */
  const BUILDINGS = {
    ferme:     { nom: 'Domaine agricole', max: 3, cout: [700, 1400, 2600], tours: [2, 3, 4],
                 desc: 'Nourrit la province : croissance de la population et assiette fiscale.' },
    marche:    { nom: 'Marché', max: 3, cout: [800, 1700, 3200], tours: [2, 3, 4],
                 desc: 'Commerce intérieur. Le troisième niveau ouvre une bourse.' },
    port:      { nom: 'Port', max: 3, cout: [900, 2000, 3800], tours: [3, 4, 5], cotier: true,
                 desc: 'Commerce maritime et chantier naval. Province côtière uniquement.' },
    caserne:   { nom: 'Caserne', max: 3, cout: [800, 1800, 3400], tours: [2, 3, 4],
                 desc: "Recrutement de l'infanterie, du simple bataillon à la garde." },
    ecuries:   { nom: 'Écuries', max: 2, cout: [900, 2200], tours: [3, 4],
                 desc: 'Recrutement de la cavalerie.' },
    fonderie:  { nom: 'Fonderie', max: 2, cout: [1200, 2800], tours: [3, 5],
                 desc: 'Coulée des canons. Nécessaire à toute artillerie.' },
    fort:      { nom: 'Fortifications', max: 3, cout: [1000, 2400, 4600], tours: [3, 4, 6],
                 desc: 'Garnison, murailles et résistance au siège.' },
    ecole:     { nom: 'École militaire', max: 2, cout: [1600, 3400], tours: [4, 5],
                 desc: 'Forme les officiers : moral et discipline dans toute la nation.' },
    universite:{ nom: 'Université', max: 2, cout: [1400, 3000], tours: [4, 5],
                 desc: 'Accélère la recherche.' },
    manufacture:{ nom: "Manufacture d'armes", max: 2, cout: [1500, 3200], tours: [4, 5],
                 desc: "Revenus industriels et recrutement moins cher." },
  };

  /* Technologies. « cout » en points de recherche accumulés par saison. */
  const TECHS = [
    { id: 'baionnette', nom: 'Baïonnette à douille', branche: 'militaire', cout: 260, requis: [],
      desc: "Le fusil tire et reste une pique. Les piquiers disparaissent.",
      effets: { infanterie_melee: 0.15 } },
    { id: 'feu_rangs', nom: 'Feu par rangs', branche: 'militaire', cout: 420, requis: ['baionnette'],
      desc: "Le bataillon tire par pelotons successifs : feu continu au lieu d'une seule salve.",
      effets: { cadence: 0.15 } },
    { id: 'artillerie_reg', nom: 'Artillerie régimentaire', branche: 'militaire', cout: 520, requis: ['baionnette'],
      desc: "Des pièces légères attachées aux bataillons suivent la ligne d'infanterie.",
      effets: { artillerie_portee: 0.10, artillerie_cadence: 0.12 } },
    { id: 'vauban', nom: 'Fortification bastionnée', branche: 'militaire', cout: 480, requis: [],
      desc: "Bastions, ravelins et feux croisés : un siège devient une affaire de mois.",
      effets: { defense_siege: 0.30 } },
    { id: 'ecole_officiers', nom: "Corps d'officiers instruit", branche: 'militaire', cout: 700, requis: ['feu_rangs'],
      desc: "Des officiers formés, pas achetés. La ligne tient plus longtemps sous le feu.",
      effets: { moral: 0.10, discipline: 0.10 } },
    { id: 'colonne', nom: "Colonne d'attaque", branche: 'militaire', cout: 900, requis: ['ecole_officiers'],
      desc: "Rompre la ligne ennemie par le choc plutôt que l'user au feu.",
      effets: { charge: 0.20 } },
    { id: 'canon_leger', nom: 'Affût standardisé', branche: 'militaire', cout: 950, requis: ['artillerie_reg'],
      desc: "Pièces interchangeables et affûts allégés : l'artillerie suit enfin la manœuvre.",
      effets: { artillerie_vitesse: 0.40, artillerie_cadence: 0.15 } },

    { id: 'cadastre', nom: 'Cadastre', branche: 'civile', cout: 280, requis: [],
      desc: "On sait enfin qui possède quoi. L'impôt rentre.",
      effets: { impot: 0.10 } },
    { id: 'administration', nom: 'Administration centralisée', branche: 'civile', cout: 520, requis: ['cadastre'],
      desc: "Des intendants nommés par le roi remplacent les officiers vénaux.",
      effets: { corruption: -0.25, ordre: 3 } },
    { id: 'compagnie', nom: 'Compagnie commerciale', branche: 'civile', cout: 620, requis: ['cadastre'],
      desc: "Une charte, un monopole, et des dividendes qui rentrent chaque saison.",
      effets: { commerce: 0.20 } },
    { id: 'economie_pol', nom: 'Économie politique', branche: 'civile', cout: 880, requis: ['compagnie', 'administration'],
      desc: "La richesse se mesure et se planifie. Le crédit d'État devient possible.",
      effets: { impot: 0.10, commerce: 0.10 } },
    { id: 'diplomatie_cab', nom: 'Diplomatie de cabinet', branche: 'civile', cout: 700, requis: ['administration'],
      desc: "Ambassades permanentes : les alliances se négocient avant la guerre.",
      effets: { diplomatie: 15 } },

    { id: 'routes', nom: 'Routes pavées', branche: 'industrielle', cout: 300, requis: [],
      desc: "Les armées marchent plus vite et les marchandises arrivent entières.",
      effets: { mouvement: 0.20, commerce: 0.08 } },
    { id: 'haut_fourneau', nom: 'Haut-fourneau à coke', branche: 'industrielle', cout: 560, requis: ['routes'],
      desc: "Du fer en quantité, et moins cher. Les canons suivent.",
      effets: { industrie: 0.20, cout_artillerie: -0.15 } },
    { id: 'canaux', nom: 'Canaux', branche: 'industrielle', cout: 780, requis: ['routes'],
      desc: "Le charbon et le grain circulent à bas prix entre provinces.",
      effets: { commerce: 0.15, industrie: 0.10 } },
    { id: 'machine_vapeur', nom: 'Machine atmosphérique', branche: 'industrielle', cout: 1100, requis: ['haut_fourneau'],
      desc: "On assèche les mines profondes. Le siècle bascule.",
      effets: { industrie: 0.30, recherche: 0.15 } },
  ];

  G.army = { CATEGORIES, UNITS, BUILDINGS, TECHS };
})(window.Grande = window.Grande || {});
